name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - acc
      - main
  pull_request:
    branches:
      - main

jobs:

  # ===================== DEV =====================
  terraform-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    env:
      TF_STATE_KEY: sam_dev/terraform.tfstate

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -backend-config="key=${TF_STATE_KEY}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan


  # ===================== ACC =====================
  terraform-acc:
    if: github.ref == 'refs/heads/acc'
    runs-on: ubuntu-latest

    env:
      TF_STATE_KEY: sam_acc/terraform.tfstate

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -backend-config="key=${TF_STATE_KEY}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan


  # ===================== PROD PLAN (PR TO MAIN) =====================
  terraform-prod-plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    env:
      TF_STATE_KEY: sam_prod/terraform.tfstate

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -backend-config="key=${TF_STATE_KEY}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan


  # ===================== PROD APPLY (AFTER MERGE TO MAIN) =====================
  terraform-prod-apply:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production   # Enables manual approval in GitHub

    env:
      TF_STATE_KEY: sam_prod/terraform.tfstate

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -backend-config="key=${TF_STATE_KEY}"

      - name: Terraform Apply
        run: terraform apply -auto-approve
